"""Deterministic standalone verifier-script export for GUI scenarios."""

from __future__ import annotations

import json
from pathlib import Path
import zipfile

from .scenario_document import GuiScenarioDocument


def generate_verification_script(*, scenario_filename: str = "scenario.json") -> str:
    if not scenario_filename or "/" in scenario_filename or "\\" in scenario_filename:
        raise ValueError("scenario_filename must be a simple file name")
    return f'''#!/usr/bin/env python3
"""Generated by KinCheckAPI GUI; no GUI or Viewer dependency."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys

from kincheckapi.gui.scenario_document import GuiScenarioDocument
from kincheckapi.gui.simulation_service import GuiSimulationService


def verify(*, scenario_path: Path, model_override: Path | None = None) -> dict:
    document = GuiScenarioDocument.read(scenario_path)
    if model_override is not None:
        payload = document.to_dict()
        payload["model"] = {{**payload.get("model", {{}}), "path": str(model_override)}}
        document = GuiScenarioDocument.from_dict(payload)
    result = GuiSimulationService().run(document=document, run_id="generated-verification")
    return result.to_dict()


def main() -> int:
    parser = argparse.ArgumentParser(description="Run a KinCheckAPI GUI scenario without the GUI")
    parser.add_argument("--scenario", type=Path, default=Path("{scenario_filename}"))
    parser.add_argument("--model", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=Path("verification-result.json"))
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()
    try:
        result = verify(scenario_path=args.scenario, model_override=args.model)
    except Exception as exc:
        result = {{"status": "validation_failed", "passed": False, "error_type": type(exc).__name__, "message": str(exc)}}
    args.output.write_text(json.dumps(result, ensure_ascii=True, indent=2, sort_keys=True) + "\\n", encoding="utf-8")
    print(json.dumps(result, ensure_ascii=True, sort_keys=True))
    return 0 if result.get("passed") is True else 2


if __name__ == "__main__":
    raise SystemExit(main())
'''


def export_verification_bundle(*, document: GuiScenarioDocument, output_dir: str | Path) -> Path:
    destination = Path(output_dir).expanduser().resolve()
    destination.mkdir(parents=True, exist_ok=True)
    scenario_path = destination / "scenario.json"
    document.write(scenario_path)
    (destination / "verify.py").write_text(generate_verification_script(), encoding="utf-8")
    (destination / "verify.py").chmod(0o755)
    (destination / "model-reference.json").write_text(
        json.dumps({"model": dict(document.model), "scenario_sha256": document.content_sha256}, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (destination / "README.md").write_text(
        "# KinCheckAPI GUI verification bundle\n\nRun `python verify.py --strict`. The script uses KinCheckAPI and does not import the GUI or Viewer.\n",
        encoding="utf-8",
    )
    return destination


def zip_verification_bundle(*, bundle_dir: str | Path, output_path: str | Path) -> Path:
    source = Path(bundle_dir).expanduser().resolve()
    output = Path(output_path).expanduser().resolve()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(source.iterdir()):
            if path.is_file():
                archive.write(path, arcname=path.name)
    return output


__all__ = ["export_verification_bundle", "generate_verification_script", "zip_verification_bundle"]
