"""KinCheckAPI public package."""

from . import (
    assembly,
    cadir,
    checks,
    clearance,
    diagnostics,
    dynamics,
    errors,
    export,
    kinematics,
    pose,
    result,
    scenario,
    visualization,
)
from .kinematics_analysis import (
    ConnectorPathResult,
    ReachabilityOptions,
    SingularityOptions,
    SingularitySample,
    TargetReference,
    WorkspaceOptions,
    WorkspaceResult,
    WorkspaceSample,
)
from .assembly import (
    AssemblyModel,
    Component,
    Connector,
    Joint,
    KinematicEdge,
    KinematicTree,
    Part,
    build_kinematic_tree,
    validate_topology,
)
from .errors import (
    AssemblyValidationError,
    KinCheckError,
    MJCFAdapterError,
    MotionSolveError,
    MotionPackageError,
    ScenarioValidationError,
    VerificationError,
    VisualizationExportError,
    BackendUnavailableError,
    BackendCapabilityError,
    GeometryCheckError,
)
from .diagnostics import (
    AgentGuidance,
    AgentReadableResult,
    DiagnosticReport,
    ValidationResult,
    assert_check_passed,
    format_result_for_agent,
)
from .pose import Pose
from .scenario import ComponentResultScope
from .scenario import MotionSegment, ProfileBoundary, add_joint_motion_segments, set_initial_state_from_home, reset_to_home, set_profile_boundary
from .kinematics import KinematicSolveOptions, KinematicCapabilities, backend_capabilities
from .result import IntegrationSample
from .clearance import ClearanceReport, EnvelopeSample, MinimumClearance, MotionEnvelope, SamplingScope
from .checks import AssemblyIntegrityReport, ContainmentRelation, IntegrityRelationResult, check_assembly_integrity

__version__ = "0.5.4"

__all__ = [
    "AssemblyModel",
    "AssemblyValidationError",
    "BackendUnavailableError",
    "BackendCapabilityError",
    "KinCheckError",
    "DiagnosticReport",
    "ValidationResult",
    "AgentGuidance",
    "AgentReadableResult",
    "assert_check_passed",
    "format_result_for_agent",
    "MJCFAdapterError",
    "Component",
    "ComponentResultScope",
    "MotionSegment",
    "ProfileBoundary",
    "add_joint_motion_segments",
    "set_initial_state_from_home",
    "reset_to_home",
    "set_profile_boundary",
    "KinematicSolveOptions",
    "KinematicCapabilities",
    "backend_capabilities",
    "IntegrationSample",
    "ClearanceReport",
    "EnvelopeSample",
    "ConnectorPathResult",
    "Connector",
    "Joint",
    "KinematicEdge",
    "KinematicTree",
    "MotionSolveError",
    "MotionPackageError",
    "MinimumClearance",
    "MotionEnvelope",
    "Part",
    "Pose",
    "ReachabilityOptions",
    "ScenarioValidationError",
    "SamplingScope",
    "SingularityOptions",
    "SingularitySample",
    "TargetReference",
    "VerificationError",
    "VisualizationExportError",
    "GeometryCheckError",
    "WorkspaceOptions",
    "WorkspaceResult",
    "WorkspaceSample",
    "AssemblyIntegrityReport",
    "ContainmentRelation",
    "IntegrityRelationResult",
    "check_assembly_integrity",
    "assembly",
    "build_kinematic_tree",
    "cadir",
    "checks",
    "clearance",
    "diagnostics",
    "dynamics",
    "errors",
    "export",
    "kinematics",
    "pose",
    "result",
    "scenario",
    "visualization",
    "validate_topology",
]
