"""KinCheckAPI public package."""

from . import (
    assembly,
    cadir,
    checks,
    clearance,
    diagnostics,
    dynamics,
    errors,
    export,
    kinematics,
    pose,
    result,
    scenario,
    visualization,
)
from .kinematics_analysis import (
    ConnectorPathResult,
    ReachabilityOptions,
    SingularityOptions,
    SingularitySample,
    TargetReference,
    WorkspaceOptions,
    WorkspaceResult,
    WorkspaceSample,
)
from .assembly import (
    AssemblyModel,
    Component,
    Connector,
    Joint,
    KinematicEdge,
    KinematicTree,
    Part,
    build_kinematic_tree,
    validate_topology,
)
from .errors import (
    AssemblyValidationError,
    KinCheckError,
    MJCFAdapterError,
    MotionSolveError,
    MotionPackageError,
    ScenarioValidationError,
    VerificationError,
    VisualizationExportError,
    BackendUnavailableError,
    BackendCapabilityError,
    GeometryCheckError,
)
from .diagnostics import (
    AgentGuidance,
    AgentReadableResult,
    DiagnosticReport,
    ValidationResult,
    assert_check_passed,
    format_result_for_agent,
)
from .pose import Pose
from .scenario import ComponentResultScope
from .scenario import (
    MotionSegment, ProfileBoundary, add_joint_motion_segments,
    add_periodic_joint_driver, add_coordinated_motion_profile,
    add_pose_trajectory_target, add_component_pose_driver,
    set_initial_state_from_home, reset_to_home, set_profile_boundary,
)
from .motion_contracts import PosePoint, PoseTrajectory, PlanarPose, PathTarget, CoordinatedMotionProfile, PeriodicProfile, MotionEvent
from .checks import check_path_tracking, check_planar_tracking, check_pose_trajectory, check_start_stop_reversal, check_periodic_motion, check_synchronization, check_continuous_interference
from .continuous_result import ContinuousContactEvent, ContinuousInterferenceOptions, ContinuousInterferenceReport
from .diagnostics import diagnostic_trace
from .kinematics import KinematicSolveOptions, KinematicCapabilities, backend_capabilities, solve_inverse_kinematics, IKOptions, IKSolution, IKSolutionSet
from .result import IntegrationSample, record_verification_reports
from .clearance import ClearanceReport, EnvelopeSample, MinimumClearance, MotionEnvelope, SamplingScope
from .checks import AssemblyIntegrityReport, ContainmentRelation, IntegrityRelationResult, check_assembly_integrity

__version__ = "0.5.7"

__all__ = [
    "AssemblyModel",
    "AssemblyValidationError",
    "BackendUnavailableError",
    "BackendCapabilityError",
    "KinCheckError",
    "DiagnosticReport",
    "ValidationResult",
    "AgentGuidance",
    "AgentReadableResult",
    "assert_check_passed",
    "format_result_for_agent",
    "MJCFAdapterError",
    "Component",
    "ComponentResultScope",
    "MotionSegment",
    "ProfileBoundary",
    "PosePoint", "PoseTrajectory", "PlanarPose", "PathTarget", "CoordinatedMotionProfile", "PeriodicProfile", "MotionEvent", "diagnostic_trace",
    "check_path_tracking", "check_planar_tracking", "check_pose_trajectory", "check_start_stop_reversal", "check_periodic_motion", "check_synchronization", "check_continuous_interference",
    "ContinuousContactEvent", "ContinuousInterferenceOptions", "ContinuousInterferenceReport",
    "add_periodic_joint_driver", "add_coordinated_motion_profile",
    "add_pose_trajectory_target", "add_component_pose_driver",
    "add_joint_motion_segments",
    "set_initial_state_from_home",
    "reset_to_home",
    "set_profile_boundary",
    "KinematicSolveOptions",
    "KinematicCapabilities",
    "backend_capabilities",
    "solve_inverse_kinematics",
    "IKOptions",
    "IKSolution",
    "IKSolutionSet",
    "IntegrationSample",
    "record_verification_reports",
    "ClearanceReport",
    "EnvelopeSample",
    "ConnectorPathResult",
    "Connector",
    "Joint",
    "KinematicEdge",
    "KinematicTree",
    "MotionSolveError",
    "MotionPackageError",
    "MinimumClearance",
    "MotionEnvelope",
    "Part",
    "Pose",
    "ReachabilityOptions",
    "ScenarioValidationError",
    "SamplingScope",
    "SingularityOptions",
    "SingularitySample",
    "TargetReference",
    "VerificationError",
    "VisualizationExportError",
    "GeometryCheckError",
    "WorkspaceOptions",
    "WorkspaceResult",
    "WorkspaceSample",
    "AssemblyIntegrityReport",
    "ContainmentRelation",
    "IntegrityRelationResult",
    "check_assembly_integrity",
    "assembly",
    "build_kinematic_tree",
    "cadir",
    "checks",
    "clearance",
    "diagnostics",
    "dynamics",
    "errors",
    "export",
    "kinematics",
    "pose",
    "result",
    "scenario",
    "visualization",
    "validate_topology",
]
