"""Kinematics-adjacent physical properties and rigid-body dynamics APIs.

Structural FEA, vibration fields and fatigue life are provided by the future
FEACheckAPI and are intentionally not imported here.
"""

from .physics_types import (
    DynamicsModel,
    GravityField,
    Payload,
    PhysicsError,
    PhysicsManifest,
    PhysicsMaterial,
    PhysicsOccurrence,
    PhysicsReport,
    RigidBodyProperties,
    StaticRequest,
    StaticResult,
    SupportSpec,
    WrenchLoad,
)
from .physics_mass import (
    aggregate_mass_properties,
    build_dynamics_model,
    check_mass_properties,
    measure_mass_properties,
    transform_mass_properties,
)
from .physics_cadir import (
    measure_package_physics,
    read_mjcf_mass_properties,
    measure_interface_centers,
)
from .physics_backend import (
    DynamicsCompilation,
    compile_dynamics_model,
    validate_physics_conversion,
)
from .statics import (
    check_static_load_limits,
    check_support,
    check_wrench_balance,
    probe_dynamics_capabilities,
    solve_static_equilibrium,
)

from .physics_geometry import (
    ContactRegion,
    check_static_geometry,
    check_occurrence_support,
)
from .dynamic_types import (
    ActuatorProfile,
    ActuatorSpec,
    ContactReport,
    ContactSpec,
    DynamicRequest,
    DynamicSample,
    DynamicState,
    ForwardDynamicsRequest,
    ForwardDynamicsResult,
    InverseDynamicsResult,
)
from .dynamic_solver import (
    check_contact_capacity,
    check_dynamic_load_limits,
    check_dynamic_tracking,
    solve_forward_dynamics,
    solve_inverse_dynamics,
)
from .dynamics_v07 import (
    ContactDynamicsResult,
    ContactEvent,
    ContactInterface,
    ConstraintSpec,
    DynamicsLoadHistory,
    GeneralizedJointState,
    MultibodyResult,
    MultibodySample,
    ReactionRequest,
    RigidDynamicsScenario,
    export_load_history,
    history_from_multibody_result,
    probe_multibody_capabilities,
    read_load_history,
    solve_contact_dynamics,
    solve_multibody_dynamics,
)

__all__ = [
    "ContactRegion",
    "check_static_geometry",
    "check_occurrence_support",
    "DynamicState",
    "DynamicRequest",
    "InverseDynamicsResult",
    "ActuatorSpec",
    "ActuatorProfile",
    "ForwardDynamicsRequest",
    "DynamicSample",
    "ForwardDynamicsResult",
    "ContactSpec",
    "ContactReport",
    "solve_inverse_dynamics",
    "solve_forward_dynamics",
    "check_dynamic_load_limits",
    "check_dynamic_tracking",
    "check_contact_capacity",
    "read_mjcf_mass_properties",
    "measure_interface_centers",
    "DynamicsModel",
    "GravityField",
    "Payload",
    "PhysicsError",
    "PhysicsManifest",
    "PhysicsMaterial",
    "PhysicsOccurrence",
    "PhysicsReport",
    "RigidBodyProperties",
    "StaticRequest",
    "StaticResult",
    "SupportSpec",
    "WrenchLoad",
    "aggregate_mass_properties",
    "build_dynamics_model",
    "check_mass_properties",
    "measure_mass_properties",
    "transform_mass_properties",
    "measure_package_physics",
    "DynamicsCompilation",
    "compile_dynamics_model",
    "validate_physics_conversion",
    "check_static_load_limits",
    "check_support",
    "check_wrench_balance",
    "probe_dynamics_capabilities",
    "solve_static_equilibrium",
    "GeneralizedJointState",
    "ConstraintSpec",
    "ReactionRequest",
    "RigidDynamicsScenario",
    "MultibodySample",
    "MultibodyResult",
    "probe_multibody_capabilities",
    "solve_multibody_dynamics",
    "ContactInterface",
    "ContactEvent",
    "ContactDynamicsResult",
    "solve_contact_dynamics",
    "DynamicsLoadHistory",
    "history_from_multibody_result",
    "export_load_history",
    "read_load_history",
]
